#!/usr/bin/env bash
# Displays information about the file `Best School`.

if [ -e "Best School" ]
then
  echo "Best School file exists"
  if [ -s "Best School" ]
  then
    echo "Best School file is not empty"
  else
    echo "Best School file is empty"
  fi

  if [ -f "Best School" ]
  then
    echo "Best School is a regular file"
  fi
else
  echo "Best School file does not exist"
fi
